#! /bin/sh
# /etc/init.d/tplink-gateway

### BEGIN INIT INFO
# Provides:          tplink-gateway
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start tplink-gatewayd at boot time
# Description:       Run script from /home/snflow/Smartthings/tplink-gateway/tplink-gatewayd which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
d_status() {
    result=`ps aux | grep "node hs105.js" | grep -v "grep" | wc -l`
    if [ $result -ge 1 ]; then
        echo "tplink-gatewayd is running"
        exit 0
    else
        echo "tplink-gatewayd is not running"
        exit 3
    fi
}

case "$1" in
  start)
    /home/snflow/bin/tplink-gatewayd &
    ;;
  stop)
    killall tplink-gatewayd
    pkill -f hs105.js
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    d_status
    ;;
  *)
    echo "Usage: /etc/init.d/tplink-gateway {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
